### ISSUE TITLE
Right Navbar

### ISSUE THREAD

**Issue by hemant030406** [DevIncIIT/sac.iitpkd#3]
> **⚠️ Strict adherence to the following instructions is required.**

## Design
![Right Nav Bar](https://github.com/user-attachments/assets/f48ce843-d990-4ebd-9e5d-3124bf2da8a7)

## Code Writing
Write your code inside `src/lib/components/Dashboard/RightSideBar.svelte`.
> **Note:** The implementation should be very much similar to the design if not exact. Try using the calendar provided by tailwindCSS.

**Comment by enchanteddev** [comment]
changed UI to better make sense
